# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRealmManagerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRealmManagerDemo
  pod 'QRealmManager'
  target 'QRealmManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'QRealmManager'
  end

  target 'QRealmManagerDemoUITests' do
    # Pods for testing
  end

end
